# Streamlit Cloud Secrets Configuration
# Copy this content to your Streamlit Cloud app settings > Secrets section
# DO NOT commit this file to your repository with real credentials

# =============================================================================
# REQUIRED API KEYS
# =============================================================================

# Benzinga Financial News API Key
# Get your key from: https://www.benzinga.com/apis/
BENZINGA_API_KEY = "bz_your_benzinga_api_key_here_replace_with_actual_key"

# OpenAI API Key for GPT-4 Analysis
# Get your key from: https://platform.openai.com/api-keys
OPENAI_API_KEY = "sk-your_openai_api_key_here_replace_with_actual_key"

# =============================================================================
# APPLICATION SECURITY
# =============================================================================

# Application Password for User Authentication
# Choose a strong, unique password for production use
APP_PASSWORD = "your_secure_password_here_change_this"

# =============================================================================
# OPTIONAL CONFIGURATION (for future features)
# =============================================================================

# Email Configuration (if you want to add email sending features)
# SMTP_SERVER = "smtp.gmail.com"
# SMTP_PORT = "587"
# EMAIL_USERNAME = "your_email@company.com"
# EMAIL_PASSWORD = "your_email_app_password"

# Database Configuration (for future data storage features)
# DATABASE_URL = "your_database_connection_string_here"

# Third-party Services (for future integrations)
# SLACK_WEBHOOK_URL = "your_slack_webhook_url_here"
# DISCORD_WEBHOOK_URL = "your_discord_webhook_url_here"

# =============================================================================
# DEPLOYMENT NOTES
# =============================================================================

# HOW TO USE THIS FILE:
# 1. Copy the content above (without this comment section)
# 2. Go to your Streamlit Cloud app settings
# 3. Navigate to "Secrets" section
# 4. Paste the configuration with your actual API keys
# 5. Replace all placeholder values with real credentials
# 6. Save the configuration

# SECURITY REMINDERS:
# - Never commit real API keys to your code repository
# - Use environment variables for local development (.env file)
# - Rotate your API keys regularly for security
# - Use strong, unique passwords for APP_PASSWORD
# - Monitor your API usage and costs

# TESTING YOUR DEPLOYMENT:
# - Check Streamlit Cloud logs for authentication messages
# - Verify API connections work properly
# - Test password authentication functionality
# - Confirm all features work as expected in cloud environment